### ISSUE TITLE
Self hosted build/install?

### ISSUE THREAD

**Issue by gusarg81** [orizens/echoes-player#73]
Hi,

Is this possible to build/install as self hosted?

**Comment by orizens** [comment]
yes.
you would need to create your own youtube api keys.
follow the readme.

**Comment by gusarg81** [comment]
Tried, but gives me:

> An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
> Require stack:
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
> - /usr/lib/node_modules/@angular/cli/models/architect-command.js
> - /usr/lib/node_modules/@angular/cli/commands/build-impl.js
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
> - /usr/lib/node_modules/@angular/cli/utilities/json-schema.js
> - /usr/lib/node_modules/@angular/cli/models/command-runner.js
> - /usr/lib/node_modules/@angular/cli/lib/cli/index.js
> - /usr/lib/node_modules/@angular/cli/lib/init.js
> - /usr/lib/node_modules/@angular/cli/bin/ng
> See "/tmp/ng-QZTJ0D/angular-errors.log" for further details.

cat /tmp/ng-QZTJ0D/angular-errors.log

> [error] Error: Cannot find module '@angular-devkit/build-angular/package.json'
> Require stack:
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
> - /usr/lib/node_modules/@angular/cli/models/architect-command.js
> - /usr/lib/node_modules/@angular/cli/commands/build-impl.js
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
> - /usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
> - /usr/lib/node_modules/@angular/cli/utilities/json-schema.js
> - /usr/lib/node_modules/@angular/cli/models/command-runner.js
> - /usr/lib/node_modules/@angular/cli/lib/cli/index.js
> - /usr/lib/node_modules/@angular/cli/lib/init.js
> - /usr/lib/node_modules/@angular/cli/bin/ng
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
>     at WorkspaceNodeModulesArchitectHost.resolveBuilder (/usr/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:85:41)
>     at BuildCommand.initialize (/usr/lib/node_modules/@angular/cli/models/architect-command.js:139:55)
>     at async BuildCommand.validateAndRun (/usr/lib/node_modules/@angular/cli/models/command.js:127:9)
>     at async Object.runCommand (/usr/lib/node_modules/@angular/cli/models/command-runner.js:204:24)
>     at async default_1 (/usr/lib/node_modules/@angular/cli/lib/cli/index.js:80:31)

What I am missing?
